sudo: required
services:
  - docker


before_install:
  - docker build -t ranganath/dockerpractice:latest -f Dockerfile.dev .

script:
  - docker run ranganath/dockerpractice:latest npm run test -- --coverage

  